import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import Sidebar from "../components/Sidebar";
import { getServerSession } from "next-auth";
import Login from "@component/components/Login";
import { SessionProvider } from "@component/components/SessionProvider";
import { authOptions } from "@component/pages/api/auth/[...nextauth]";
import ClientProvider from "@component/components/ClientProvider";

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body>
        <SessionProvider session={session}>
          {!session ? (
            <Login />
          ) : (
            <div className="flex min-h-screen">
              <Sidebar />
              <ClientProvider />
              <div className="flex-1 bg-[#343541]">{children}</div>
            </div>
          )}
        </SessionProvider>
      </body>
    </html>
  );
}
